### ISSUE TITLE
Ambiente de Homologação

### ISSUE THREAD

**Issue by Gustavo-Nogueira** [fga-eps-mds/2021-2-PUMA-Doc#17]
## Descrição 

Para que seja possível apresentar e validar as versões do projeto, um ambiente de homologação deve ser configurado e disponibilizado para os PO's do projeto.

Para tanto, deve-se verificar o estado das pipelines relacionadas ao deploy do ambiente de homologação que foram criadas no semestre passado.

**Comment by Mexazonic** [comment]
https://www.youtube.com/watch?v=4PzcfgK2voA&t=1s
