### ISSUE TITLE
Treinamento JavaScript

### ISSUE THREAD

**Issue by Gustavo-Nogueira** [fga-eps-mds/2021-2-PUMA-Doc#4]
# Treinamento JavaScript

## Treinamento

O treinamento deve ser feito através de vídeo-aulas curtas e publicadas no youtube.

## Conhecimentos a serem adquiridos durante o treinamento

- Variáveis
- Estruturas
- Condicional
- Loops
- Funções
- Promise

**Comment by Eugeniosales** [comment]
Foram realizados alguns vídeos curtos sobre alguns conceitos básicos do javascript para quem está iniciando.

1 - Variaveis: https://www.youtube.com/watch?v=mrdfqSOoGWM&list=PLe_X8N-b-VsdDe8Gn3gtvvwaK04buZz2g&index=1

2 - Estruturas: https://www.youtube.com/watch?v=8GkKUrPYgNg&list=PLe_X8N-b-VsdDe8Gn3gtvvwaK04buZz2g&index=2

3 - Condicional: https://www.youtube.com/watch?v=1IXwfxtxEeU&list=PLe_X8N-b-VsdDe8Gn3gtvvwaK04buZz2g&index=3

4 - Loops: https://www.youtube.com/watch?v=wkK_R6dI6wg&list=PLe_X8N-b-VsdDe8Gn3gtvvwaK04buZz2g&index=4

5 - Funções: https://www.youtube.com/watch?v=cGlApe5z9wk&list=PLe_X8N-b-VsdDe8Gn3gtvvwaK04buZz2g&index=5

6 - Promises: https://www.youtube.com/watch?v=8wL6KKkyFPs&list=PLe_X8N-b-VsdDe8Gn3gtvvwaK04buZz2g&index=6
